export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_START_DATE';
export const ALL_DATES_ESTABLISHED = 'ALL_DATES_ESTABLISHED';
export const ERROR_WRONG_DATE_TYPE = 'ERROR_WRONG_DATE_TYPE';
export const ERROR_START_DATE_LATER_END = 'ERROR_START_DATE_LATER_END';
export const ERROR_END_DATE_AFTER_TODAY = 'ERROR_END_DATE_AFTER_TODAY';
