export const FORECAST_CALCULATION_REQUESTED = 'FORECAST_REQUESTED';

export const FORECAST_CALCULATION_CANCELLED = 'FORECAST_CALCULATION_CANCELLED';

export const FORECAST_IMAGE_RETURNED = 'FORECAST_IMAGE_RETURNED';

export const IMAGE_REQUESTED = 'IMAGE_REQUESTED';

export const IMAGE_RETURNED = 'IMAGE_RETURNED';

export const FORECAST_CALCULATION_RENDERED = 'FORECAST_IMAGE_RETURNED';

export const FORECAST_REMOVED = 'FORECAST_REMOVED';
