export const FORECAST_CALCULATION_REQUESTED = 'FORECAST_REQUESTED';

export const FORECAST_CALCULATION_CANCELLED = 'FORECAST_CALCULATION_CANCELLED';

export const FORECAST_CALCULATION_RETURNED = 'FORECAST_CALCULATION_RETURNED';

export const FORECAST_CALCULATION_RENDERED = 'FORECAST_CALCULATION_RETURNED';

export const FORECAST_REMOVED = 'FORECAST_REMOVED';
